Updated codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -2,26 +2,35 @@ workflows:
   default-workflow:
     name: Default Workflow
     environment:
+      vars:
+        FCI_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmQ1aDB5M0hMemZhOVloU01GeXZYUy1NWjUxbHAzMUViRm9NTTI0SjRUZVF5c0l1V3NHdm5WWHVDTS1raDM0azF2MXMya1AxaGxqUDVDcHA2Njh5NDhRbW1TX0E9PQ==)
+        FCI_KEY_ALIAS: app
+        FCI_KEY_PASSWORD: Encrypted(Z0FBQUFBQmQ1aDB5UDZfaUtLYWttdUtVdEUybkIzUm5uTkVabzFDajdRZ0dmLWFyZElLRllMS1NVWnVzOXUwUm5fN2lZZXRmZFFnSFVNcUNFZ2Vld0tmclVLaXhPT0JsTHc9PQ==)
+        FCI_KEYSTORE_FILE: Encrypted(Z0FBQUFBQmQ1aDB5bGhkdEVsVWZxQUczYXh0WnJuWFR1a0FhckNLWHUxUHVjbV8wdGo5Y2VyVkJnbzNVTmNtaEs2SjFVaHF1V0o5NDJmcnBEX3YwRW9ZM0lvTFFvSjNhSmVKajQ2OGRiT2FlVVUtS0t3blI5a0tQSFBRUkZFVnF4ZDNSd3cxSWFrV1M1SzFEX2JneFJVLVdFWlVXcGN0YkFoaEhqSnAwUHBwWWdUZ0NaclhlY042RGtOX1BxRWxDRmVWSmFXUk5wUnhndmw0Zm9TM3hWaFBneE1YdGdlT0sxY2RQSXkyRGxUV1RTOS1QSjRVMHZSeENHa3hZVV94TnJiVm0wZS1ldWdIcE53aEFEbXJOOWFNMksyOER5LTZFVW45Y0lwcW5DOENZWDdYcVdkLVNUajhLXzVRUmgyR1J5Rk5kWV81TmphbmxLYzFyUXlrM0ZwUDZHaFA2VnpkZi0xUkdzLUtvYlJsaTNJazF1UWxwOHZSX2N5bkg3WkFOY3YzVTBlSkstbjcySnVyRUc4aUpyRTZLbWFqRERZUXFobm1URmhHNGpxdW5UOE9sZUN6LThCenJ0NFdfUUpUM1BxRzd6UVF6RWRPS19GS3Y5a2FZU1BiTl9JamRJZkp1ajBJRkozOWNBdE9lQXRSM2IwaDMzY2E1RS1BWGR5d2xTMU5aX0c5MjdJMTJyandJY0taUHE5N2pPLXR6MTNQQVdpdnhRYnFWc05JekdPNFBYMDZaUEUzUzRYRXVtVmR1UnBscGZIdmVMMVVVYnRaYVpqSmVxdUY5Y2ptVTMwVGJ5M0tmdU9rakVFWnc5YUJhbGJpOWl1c05vZ05ZaWhVaElya3UwRzNZU01ZZzhucVBwS0JOelBuSzNFcUczTFNGTUFKWTFzcFBWY1NWYVZieGRoajBYWFBvZXlGaHBhV29hejFzbXhsYjJMY2lOVXExQk9aTEU5SGlMbko4QWZvYnBvdmJqSEFiY28tY0JZUU5sYTRKbWZzT2NHMW5oaFpPV0VrdGxRQlZJd3NVSzBTdmEwczJwaGYtSG5OVk9hdUpMY3kxbnN1OE5GTlJNNFNLQ2RQdkpiaGUxbVJ3ajA3OU9vSC0wczNvSkI3bGJWNHhqUWtlaXp2bERxX1V1OHNyWG85YWlOaTlTRmZNbTNoY1BfMkgzUWhILWJFYXZNUHhJTU9ldEN4d1pmdjdDWmxfeFhlUnl4SURGRUUtQnE3bW1lQjFCSXBsNTJpYWcycHBfRHluVllUMmh6M3VBcHBtLTJ2NHpUX0tnYWxDdk93R1I3X3U3TzZRSVdMdEpPVmM4QlBQSTE4TXlHWTRScmlXT0xMS05wYm5hR09Ba0pIREFWemN6ZHNnSk90OFNWd1RXSlg5eER4by1WQ1d2MDFhUzV4N2RUVkxRcEQ5TUFxVktlcHNsM3dJbFpXSzVkazktY3BVVjE2a1NNQmloRHJYUGtyR0w2RzBxaEpKdHMyS0EyRWVaOFN3RzlXaGdDSWNqNE1XVG5CQlM1T0g0T1BkX3BQOXMxTWtVajhFdDNabTJPWGZuT3ZlbmRMMk5ZN19SZVgwYVZwdEE2VDU3ekdwemdNaV8xRUdIS041cUIyNGpZZjRVUDVUN0lrR2d5UTVQdUtIbVM5WUNKMUk5NXBnZ19YbEhJeEhucmFieUhQWWJlNWFYNVhMV3R6ZWpyZ0lHQ05kaDJ4YVBfcmNXUko0eU9NbkRxbEo0cTdCV2ZYX3lRcGhwNFN1OUt2bk9KWDVmaDJrLWN4SzhDaElmWGNoeXlDWGxRQ3NvbWxhUzhSNWRsN3o0SkZ2Yk13QTdRNzF1S3JqcnFYejZidHQwTkg4SmZockhWaTFYQWxCdXpYZ2lXaFJmTXlqeFlqZTMtdVlHRFhoOTdlY1M4cjM0QjdMMmFQdU5FS2tFdmk3Ylo0dDc2cVVpVl91OHlYSWo5bXlGbkNyQU5NanRRak1IQnlPeGo0MlBfalNhQzZTdEJMeGJrdVlSanJLTWRZcXdyaFd2emNCYlZxVlR2YmZHVldwNWZEamo2Q1Z4a2hGZHJ2ZGZEbkZ2OUNLSDlQY1d1ZF9TRDJDNzRIelduTmNiVVpkV2Fxc21qNmNXTHRWUVdnWkx2ekhpQWpwWXFscUY2c0VvOUNhZjNnTjNoNklfTmdHU195ckM3NEhXQmlEb0dKNjJLMmMzZU9pdGRDNTdxbzlWUmhTX2ZNRE5UT3ptei1ZVmtCSnE0Nm9yUWFsa0pJX0paUzhYVng4WUxkZ2NCRFFGNTFrRFY2Sm9EUUlQTGRVcEJ1MlZvLVcyajhsQWhwdWQ4cVJCSHJzcTEwZmFuXzl0WjdUaGZWVERFVjcyRnhxdEFVemJZMXhvc0lpY185RXd2M0YwcW5HOG5PYm52SG1ycUFIUHhCdzE0cXgyeFFwQ1pwM2RKVWJ5UTJxYmEwN18xZkdJU3hwZktVLXZkbUZuanZSeWo5a0NaSlBNYzZJZ1NJbC1ZUnJ4SEpJWThPMFlZZ1NUalVodnNud3d5UWU4MXBpaVI5blduU3E4Sl9hLW5yOUtYcGlzZ0lDVVZYMm9pQ3V1TXhRUnZUZDQ3OUlWX1M3aV9VanZUdDM1SHRfeWh3QXVIWVZra053U0ljcm1wbjVBdk1XalNvd2dCUTY4SzlhWjFHQ3VCLU9kQXRSVEtqZ0hoZDZIeFptUXg5bktPTzJ0UGdlOTM5aWI3aFkyX2JIb0k4SXNYcFpVR2paeHpxOUxJZE9vZGY0cEcwbDVMRVlIdjFMTnJqZ2J0YW12ZnNfTEhic3FFb2VXb05iZThBV1BkM2NGckh4TDZVZXItaEJJX0x2VWFjSk1XZk9UeFpsQVF5OVhfNEZjMmdvUGpNNmNhdTZ3d3dmREtUNkJnUUhXMmgzaTl0ODNkNjNDd0w3RUwxcnhMS2N3MnhVdGkwRm9xcG1mOFY1OUxGWWtfRXRnQU9FTGlFdTktM1BsTGJkcnVkaWlDb1k3SnNrR3hUSGV6X2lfbWJvWkxfOWhhM0NSdmdkUXN6ampwOGgtbFZ3Vk5uT0NUdXZ1SmttcnBXUmkyRkY0WERienFjRkJXLUtaUjZNSzVldDd6anJacUd4andaa1pabWVKYUpXSVZpTklkZ1cyZHZHR21MT19YOGN1bjNhUzg1dEJRMF91bzZSeHFzTlY5ODdfd29ZTmVkdjRNZ05jY0I5UzZ6NW5OaVNmenFwc2dpc3RVY00tSjFReUtKM2YteUlIRW1pXzJiRE5JYUI4MVN4V2UwaV93dk4tVEd4OXlHTWNMdnZUZGxtYmZqb2daNGprWVZPb2hqa0xQaEVWaU43YjBoS08tN2JFZUl5LTI0MTBsRG9sZTFmTTdMbWhrSkUzTk95ZGxTc25TVkxyVUQ4bUlUREloVng4TjBFSWhLOWtiRTBibFhFZERqUjZ1WGhZc1hXTEUtNnFybl9zOXJCVnRpdG5vNFdIb0o0eTg4b0xvdXg0c1kwX2NETDN3R0VBZzVvQTR3aC05bkcxZWMxYThVbWtaZTlDd29SVHB5M2hWQkd2SzN2OTFQTmYtUENhREZaZlQ3bjBURVdjNWZ5blVWUGNJMDRuMVpGV0tLVjVKN0RHc2VCS0tPbDRWQUVHaGZCMkkzYkF5b3JTUjZkTnQ2cDRXemJYaE43UFFsaGVnekFxTmV1SW4wMTBSTzhYaFkzZ0lUd080d09LYWYxS1V2QTgzYjdrc1BRMlNMazR0cndRWWh4TlBUSmY2SFpkOUpSWFRueVZWRDIwYmlZRDU0V1I5SHA3VFZ4QjQ2MV9ZaGRISVZma0xGVnJhWXlBTllfbWJGdGd4VlhQLURxMVo1YjM5emFmcWFBaWMyUmtFNjJsSTV1aFZSTWxtd2dKSnBBcGJXcnRRLWRCTmlwZ3AzM29GUjBuSUNNNTNpOERGd3U4M1ZHZ2pscWthTno5Z3JmS0N5bGN4N3BFM0ZVSDVValBsQ0RaRGdoUTRTQzJYVUhOSGpoZ2lWTGZ6eG5aRE1SN2RQVXl4czg5LUc1bS14dTE4OWVqbURWSlRjTzNzSGhSYjBpVXdESVNYMkhtX0c3TDdaZ0Y3emJ0UXdmYmx6YTBnV2hKZ085ak5Bc19SbWNBQjV5RkxtRnAwaHlmMWs0b0l5MlFfcWxxWUw4dFNiTFc5Q3RvbDIzZVl3aUxjNXlmMzRUMDduaUlDS0dBVURzTGxUd3Jzd3hhbXZlSFVUZnJzNktxU2REUF9Rb1U0V1F4dnRVWEdQRVpTZTVTajFCQW9NOEhtd1JpeFNCczA3TWJUNEJTeklZX2dvZ3BaSmZ6SmlHYnpYeUdZUnQ4ZmZhTkpnY3Nta0dmd3VvcFJSQjlRR1prWjVWQmdyLTRaWkRWXzY4MEFfR1lDS0tuaEFVXzVjS2FBVHc1UEVZZ0lTRm9yRURlay0wVHVFMFN2YkVTLXVmSk5EUDVvYXBSZ2xpV1p0YWVsSkhlb0trRWplU09QM1lxak40cXBDdTlCOVJwZzJUMUFHYXVwMjRxUmVOTHdZazNYb3BJY0txZm5tRGRnNlo4dDd0a3hzd19CRnQtQ0RtMm1xSDhqZmhnU3VxZmhhS1NtamJXOVd1VnBacEFMNEFwS0Exdm1NaUxrT3JMbGFZdDVDRFJjSDlVSWV1SVk5c25KNDdlbjhBV2dWbU1TanExN3dBS21mRGJlblQwQm5hZXhBRUw1WHQ2dUI3eWJwdXJUa0VTS29LMGlQMUlVWWxXTWpFSmo3XzdPanZTNVRDSVpGaFJyd3pWRktFM3dfMi0yTlVKZDlDRjcyQ3BKTVhXMzZGSDlSRTMxSEg2ODQwNzM2TTR1RVNCZXJST09ka3NKZXduUVEtZGxWSk9WcmxJQzlsOTJsUDBLY2wwd2xfelN3Qy1tQVhiaGxnOGstbGtaODZjYktlMmxGMl9abDNPc0hhQzU4Q25JdGtrQXBtZElQeGhFSlZaX0xmOHlLQ19CWkdnNE9FSXZaRGRfYldRN090Wm5GLVptRGJnV3RfQVBfQmdjamozUWY1NGNPeWJyeHNNekJTbDJYNWtyMDFVR2hkMWh1ajNrZVViT3RXQTIxM21CaVZqNko5TDZ4WXVrcEhudGNVcWdZYmZYRXZSWHVKaTVhNzNpYTk2S28zdklya1VyMnZ2R0ZnWldQdHdOSDVpa09CelpUc2k2akFvSlBZanlfMjltaVNqLWJBVGFJcmZJQWZKbmpqaGE5TWpibUJhT1BveHh0ZzFReS0wQi1ibXE2cXZJMDJQSk0yXzBnOUZOOG5TQlVVdjJOd3g5VGhoRHhWclFBUm1KTWhSdHRIN0F1NHNBRnppMHV4dmhPVHlCTHh0SnJBVlc0aHZ5dW5udFpxSTZwRXM0TC1iTFJlb2FQNDlONmFTcEpOVmwxanBBYkhRVmd2dy1MTHBnRV9ZUzROZmFIek50dDZpSEVzTURZM1lGV0w5TFNPUVRzQ2prQVJ6ZGlsNnZhVnhJd2hMYXk3WnE1WjRUYl9rOUVyTjZMVkRKTGVha2JmUUVIbkVtTGhqVlgzRW01dHlDZ0lRcnhfc28zNVBQN0EyZUVLQzVRY0xjZnpmS2FKUlZ0MC1HR0R5Zk5KVENqSGNBMmZRazdwd2lyQjgweURNMnFKR0RpeHJZRVRNd3pQME93TFlkekFWdkJ0OThQYTZySFBuazJ1R1I4M01yQWZwWnZHdVIzYlh0TXY2V1RySDhSclBrcjdRTDNHLUpXeUhpNjNqNEpWaDFjMzc1blB1SGhBelpaZWFSblBpSGFmVlZ3V1dsSzNnbVdCcXdpQWEyeTI5T1pPS2toSEZsRHdzUzIwRlV4T3RraXl1M25oRGhpNHQ2cVlMMl9kbmRzV2lLd3FuQi1zMkdRbXFTb05BaEJqcnZpNkU2R0RqV2ttR09jeDRRM1JSWjROU2tTS2p6aXNfd3BPUUZjWExuM2NRMEhhc3VTQk5jei1tNFh1YW43M1hXMjJWSml0eUVaUEhodzItLVlTZXhka2p5OGh2VkljV0pWWWRpM2hid2pQM18tOTIzQU1sVEJPeTRqdTYyamJsU3BYbU1qcDBBdExmWWRIR3Zqa0x1Q09xbjBEbFJITjVMQTJSeFFSa2Ficm1aeVdvUlVrUzRLcUNjemNBNlJUSXZ6TkpHWWc4enpIVlFWZnR1Z2F3bEpFcDJNVUlZQVhsdGZoOUdwTHdfcUs5OGNndnVQV0l4UG1OTHp6TDRWNERSYmtkdlk5NjZ2cFJqc3R1LURTd0M1MS13MEV3b2FUY1hGMTl5eDA1OG93aW4tcURELVA=)
+        CM_KEYSTORE: Encrypted(Z0FBQUFBQmQ1aDB5REtwZklMNFdyT3VVTnBTNjNaeFpqSGI5VmFyY014X2xRSkE2ODlTNWpMZjN0S2RJUy05b0xHNGxqakFWYjBtMzNvRm45MlpGRzBZYkZ1T3lvMk53MVJvN19hU3BJRmxWVXhIdUdDakNOZ1EwdEVhZkxnYWRyY002WUt4dktVVWNUVnFfdnVPYUtGXzBzLVdvTXI0SzFERW9mVnFkNXNRTHZMbEtPRVlvbURSWnZkTnJXN3JnREszYzZWeHQwT0FONmd1VlhUdk9PYzJJalFldWhvazl2azlncXlwemdkZlJxZ2ozR3ZQNlBpR04wTlUzNlZwQkM1NDBTdnlzV280ZVFwZkl4UnNJWnMtWDhhUDliZjBtQXRRdVBxUE81amp2S3M1dzdTT0tDN3AtWHp6U2VRMm1GYXpoaTZvOEFKZVczMU9lNGtPSG55S3dNSHJzd2lNMDdOUG96ZjRBRlByOTZLQWVCSEV1c2Z2RVpoMjA0Q2lYQXZvcmhuWlp5VUp1blA3Nk44MnFKSjlCOHJ1eXlYcDdyTGozSF8yc3BlSGhjMHR1VTNuOFFmWE5HZlQ3aDh6cURvM2RKaHJ2eWFGVC04QmhKSFo3aGMycnhuVUZYOURSOTJoTXJpZFd2VjNjOEpsUTBmLUI3R21ZWThBN2dRT0NKeUd0SkcxcTJocnROY29wX04xUHZDVU15RDBydnpfUnBzbVdHSlZqLWVDQ2V6Z2VBSHJ0ZXFiZ1JwbWZJZVNFM3BmMmtjZ0hOc25ib0s0cWpUSm11dEVxSzdhMV9FTDFLZ1BEMU9RMzNTRkhOTW01ajdoenFBZUdIOXotOXRpQmJFQWMxLXRDV19pR084TmlKRGJzWjY3eHZrbDFlTFI3TXY4cGRNdGl5aHlDcEw1WWhvX01uRHdQbEN2emVrV2s1VUZxYzJvSTF6QTVtUGNOeV85Y1diU0tBOHVsRk1USWlEU3lJR2JVd19vR0VtemFoWld1NmdoWGRnRFZoaHlIMXVJT0stZnBUYjJJdndZck1PWEM2NkNraGhWRTMtNE9jQkhKQldaOGNlTGZTd2tvNGFjZEtweGJlNWlfQThjQV9BVTgxODM5eXBCMnFreTV2YmRwY3ZlVTNqN2VRNGF6bTdBaDlkN0xTRk9iQXF1RXZLNHZkSzhlQmEwa0M2R1B0dW5CTTZfZXFTNXNjdFVraUQzMkNhTFBNLXdQRjREb0NTUlVLX3hoTUJzTzd4X2lDWnA4dnBCaFFOWHFMakp4UU9iME9WRzh6YV9Gc2hWMW50Ym43VEc5dHRyZUNOSzQtdGhEYW8ta25CZ1V4cnoxTlE3U2pJc3BBNklDMEtNaDl1Q2RzM0U3THgzUVQ3SzZYcEJkRUFKTmw5X0QzRjlYQVpSbWhoWXNRTjdMQzNQWFpGUlZGbWhqdWM1ODI1N3NOY0xyVng0aFdqRnRwVWxrdFBXTzV1V0E3eFBfUGFzbGRLOXpaUjA1UFNPcGNnVEJhMXB4TnZ1Vjc5UkRLWkRlSmJPdk1rNWo4UFVSdDBEaFVPVUxNbGotUkNPZzRRU3haZk1WUzVxanJaVE9EVUF4S3AzWHFMbm81d0twbXFMdFVwbWZpMVdrYk5naDVCeWN2S1ZDLVRyZmE0bUkzbFktUDBIMW5WV20xSWFzUHVmWWx0ZFlERkxxYUlLbEJqZmYzaGMtczRXRzhZTEh5RXA4S0g5LTlaeXFPUkZmd09pSC1ZODlXcEtGOUVFRGN3ekd2QnNGRXVob3FmSW1ZVW1uNzRDSjQ1N0RsNWppOGpUeUlrYWg3S0UxVk96MVBpdnVVYlVLQVV5dXBzZWlyOVduTHljUU9WaDdLSWQ4R1VkZ1FpSlJPVXhpUWFmNHZwaml3WjdRN1F1Ym9yVkgxVnNLWnZSSzJBY2JmXzhTZ1hPei1JY2V2a3M2MzJZTmNPYzQ4Nlh2S0hTeXFOMmNMY1BxSlJhY29KQW9kXzRoUDRlZ09hQVQ4NTFhTzM0Vk43M0d6a19zYWhwb3AwdVFVaEtDWmxxMFNXUnhRU0dPN1JqV0JtRWYtMEE3eG5ZNFcyT3R6QTZGZDJqNmc1U1l0NDhWcUtLR2pTRkxQVDlzcldRTjQzRERkbUtVSDFDcWYxOW1tZmNNYU9BT2VISFVFVy1FdVFHeXpmMEZCTldQV1pQaGM1amlSYW9GNWppM0tCOUlKeGNXREFlV1FjLTltQWQyQTJmM1ZxUmxFRGVlQlFHSkZ1cVk0Ykh6YS11UXJJcmZJV2pVR2l3b0xocXY2d0hFMXZsTGdFNktpUzIzLTlSc3loQVN6NlhRZWd4aEFUNGVPWlVrR3h2ZEN0bFZHZVozWkxtSDJjRy1ZTGJhWEZFUmRReEd0NkdTRlROOWFrZ3hQNUFWZFVBY3hsSTdYMXFnYXNfcmc4V2xIRlp0ZDFmRXE3Mk1vTlFxdFBYNVNteEFtbE43azV4X2tKY3JhYVAxenJmOTA3WTlfWnkxRWxvbnNFcFAxMUg3N2tlNmtRNEFGYXBVc1Q4ZzVnZDdmckJWeU5MaktiMG1SNy1LSmtrajZWNlhHdXFhOVktb1p2cUdWbzBOdXJRckFUTmJHYXpSWTNuX1JtM2VSb1N2UnQxWjRQOG5Sd3h6eDNwNjBRQ09vODk3eXJSU05HQkJ6dFRvRUd3Nmw4dEk5MFItei1fODAwWlFrOVV4Y05kYXRUOFlJc0FLWjB1MnFhSEtUeHlmTFF0MDN0SVN2RS0ybjhTS2R4U21JSXVjWVppd2xJYW10dU0xaDdBbG50cHRwTXFpRE54S0RXU3VUbDdCY2lkaFluek1QX3pRaExzRUFqbWpCTVNIdUk5dmt4N2hGMUg4VGNvYWRSTGo1RC1zRGlsVFNYclFsbUFWTWZtWUFCRWtvVF9zdHNreml4T1p6X2hKX2VCUE9obVdMdGFMa2M3b0ktQ1hSYkdCbkJSNkZ5TVVFLW9DR0o2MnJESG4yQmphZ0dpVWhJQWVpV1lJNENKZWJ1NjZ4dHRBcEROdUpFam9zOWh6NkZzekJqYlEwZk0zeThXUDN6YWpPUjJ5V29YaVB4Q2NQNUVwWHR5aTU4LTN5RkNhS0hZVmpHTUppSll5YlVIWGZSVVhXSGd0QndYS1Zfc3lpdzlLWnFpVUptT0V0dkpQeENJVGM3RFByY2xqaHlxUEJtZmxqWGJzMmVBeGFBQURzN2ZfQWZsUDlsTTZVMllHZHhkblA0c3JROXNFUzBGYjRRbkp3MnlkQXR2THRUNkprSnc4NjNnTVRsZEh2bHhjMk9qMDgxOU9xd19oa0E4TnJ3SUw5R2w1bHdkclB2aFBWUHZfUWVvX0JjaGU4M09rRFhleXNNVWRyX3NHbXR2WVE2OGF2UTYyM3RYbWtsX1ZtLWZ1ZHJlUkIza1RWanR2UGstOWd2anJTUDUyTmhNcldJQ3M5VzE4b1pELW03alRrRVBpS2tUMUNubDg1a3FfZUtkSmhEY3ljNnFjbVctTm9jZTNZa3p1cG1FQjFDWUVxUzN3UVJsWnhScHhldkFFWnNuUlREdlYwTUhtRUhKUFg5MU1wX2pUWjBKbGQxZ1d6MjhpMkZLQUxxUDdGc2x6cEFkczZVZTZybG81SFB3cm5DSGNMTHNsWHhxRUtWTUI4YWRaYkFvNWVnTzVlbzlWcXJUb253MWhMV1dreHg0WS1KMTZ6TGpDVjY0ZkNkN0ZZUl9nQVRWcDJqM1ZubjVFTURJbFMtRXRZTnlKRFctejlRMm9Uem1sSTBIcTRtckRBZUtuNHowTUk5VjZoTjVsRzhDTEE0Y0NGNHo2YXlCQ2hhcm9BQUdQSm10X29WN0F5VTVKUUFFcGJ5bzVsQ1lzanlUeklablZWcmVCd2lmTEJ5LUNTREk5QWZDQmQ2cm15bi02b0FKZUU1RlMyRFJmd2pZM3daTmhWWklJMWlzdzJOZC11SllBVEZUdjE1UlZLSGRtblMzdjZydXFyTE5PeXh1MmI4YXpLMmlCdGVSX09jRlFscTdmbHBmcDBwMnFmN3pzWmJJcklRQ0JsdDFON1gtTHhSVkdOaU9YSVlHak1XOXYydUVGOW83TTloNE9OeC1zYkRUUTdyX0U2NXVueUFsX0dBb19oZW1EUGdFRkQ0akVPU3B5Uy1vdTdDZlVvYXRObm1RY2dZdmFMbHhjbW5FSzFTanNZZEdQSjZnZGtCTWJrUWN5TzNKd1hiTE1NWG9kRDhFaDBSbjZlQzdYNmpveko3d3JJR3FTQjlxV2xZUnNwR25iSml6eWU2Skc2SEdwTGk2QjNRc2NobEJEOFlySlNnc3NSUXVScEhGRVlvc0lJYmgwbVVpN2FlZFVUdjhyZm9BS3Njc2FWRUFrRE9xM1dFa0lXWm53cUI1NzhDVGdVaUVEVTdiS04zUXN0YVVCUHJ2VVZLUm5NNV8yY1RYU1NOTmFUdmFOektYcVh4V3NWQUwxU05vd0JKa3hMTnZPYXZFUFIxZGxxTmRKYmRQNjBvQ3I2S0swSEkwSVhrLTRndlBvR3k0LXRpclE2Wm5HMTZ3V0ptWFlvLS11UkN3b0ZNMWdoQkdaLTI1RU1iUWhkSkNVNC1XVzk4LUNQbWpYXzYyWjNLRzF5UjRKRWtlNkRvdmtrODhLNnowTzZrQzVfdkFNS3luMW9qai1SMzlaTERJaXB0ei1VTVhZYWltMkJubTRRck4xdFE0RlJ4TERKSlFPR3ZOX3dxTWNZTzdYd2YzVmFkUE1MWC1TTm0xejIzbVJsNUZvTXhJWG1xc2Q5T2h5ZWVWdktsOXduTk0wV3VKdjRkbzZGWDROU3BoY0VsVUJWc2VFQ1poNEE3NXZJVlQzMWpRRXI3OHZINS1pZzBRcVF1dXVPSGRXTjg5dWxoVzJWQnE3dWlMU0RFa0pVaFE0QXNrQ2paM1RRdVlueExoTXRfZGswc0pReVlrV1lpSmhWNjBRYTk3REkwb0NTZnVIeGNSaTlJbkRHdERvdGhHeTRHSzNqTzc5TUxtVUp6NVZOOGUwUTZVZl9pN3NPX0VWY003ZzNaSXBBWU40MXdzZ2thTzhfQWNZSmNuU1NzdXB3OF9OeXh3WEZ2TFZCMzR4NndXLTF5YVlvNGN6bktHRkdLOEdGOW9KOE13QktxQm5NNEZHMWFiZ2NPODBxNmtCU0RPSDd2UGhvdkRPZXpiMHhkcGFyNXRjc2tYdUhLaW9uRzF2OTRmLURUcGtEeEY4bmdRYTFFYVlmRXRJVVBEVGltdUVockVCV0psaHRGSDduLUR3VGVYUThuYW5EcUhYaGFXQ3ltaWljekMwQXpHRjhpRkR3Z0RyYlNMRXRleWM1TzRiX3dsS2pOY3JXZVdwejhQYTdSZzk1N3dLaU9qME1wUkh1TElEQnNieFBVOHpZbU1ud19YU1VubU4tUjRpNDBpNy04M0hkZVNYTkxiSkhiLTE2T0FQY0FDTGpqcm53S3dZRlNadllNaEJUQ0lldjFkUWFVYmxuaGRSMG9jTnU1UVQ3WWF1d3JreHl1cXFLbDZnYkNIb2J5RWpxSjdpWmh5blRzWEJCZ2VpRzRDdTJYdllvMTJOcmFxWUU0UEZFcHFDUVZDTUZtckhfZUZpSmRnd0xiSkl3RUd6MS05Nks1Z3hoeUtaRVhfSjBhc2ZhbWRCOC1ES09LMV90amZIRGZYNzk1V3g1X3FMNHhnTGZ2cTlJUV9TQ1BrakxqU3Vjc0dvX2FoS2NhUUkzNFF6QU4zb0pORnhqZ2NDZU5acW9raE9UNmhsY3BZZ0lRZEJIMEVhME1IRk5ONWpDQTlaRzBXVGNjS04yc3ZPRXVmUVVjMV9vTDNnV21VZFUydFFHak1sQkk2UWs4cTRJX09aRTRvOExlY2paZjFqSTFVR19aVU5vc3U2VDFLcU00OS15UUZEa0g3dG9Id0N1MXZHbW5sUXYtUlBfQTdOaENKQVdJa0VzZG4xZ2RGSlRIQTdHNGhLZHRySjB6WHFFOUNrakphaXdOQ1RFNlR2QS1kSEZCc1ZxTjNvLWJCQmxTRmxjRERUeU83bFF2ZlZLLW5fOXRGQ1JDQUQ5ak44cGxzbWtpNWl3RjJwT2JBSTh1NWoyYXVNU2lLMnJ2d3VHUU1SOTJXVXNnall2blJpNkh6eFZmYXByTERsUjNZM213MmdYRjM1T0lJRzdPZlo5V1U1eVhwUmpHT2xVZDRLWTBCNA==)
+        CM_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmQ1aDB5cDhnNlR1aVpRVDdiZmRVMEVaN0xadktUZFY4OTBKbkkzbWtQT2JpWDVpZGE0NGY2eko4Uk0wS1g4cTR6SXkwV1JTTlZ2c2hJdW15NFBYZjFPWXFlZWc9PQ==)
+        CM_KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmQ1aDB5cEtOSEZsMnBjdWhMNDdvU3Rybk9zMDdFSDNqOFltRVV2dDFaZktZMzFsX3FsMzJxNUVlb2h0R1R4WHBScjBGMlg5LWtIMW5Jb29DRmNtRTFIaXJodGc9PQ==)
+        CM_KEY_ALIAS_USERNAME: Encrypted(Z0FBQUFBQmQ1aDB5by1uQTd2dS1hbnNsZnVIM0Njb1Z5eGc0cVpuQmx4ZmlYYTRlemVLclhxdW1KbnhndHVsTGNqaVowdENURl9OZHROQWRsUE9aMUdwMWZGdGVqYno1ZFE9PQ==)
       flutter: stable
     scripts:
       - |
-        # set up debug key.properties
-        rm -f ~/.android/debug.keystore
-        keytool -genkeypair \
-          -alias androiddebugkey \
-          -keypass android \
-          -keystore ~/.android/debug.keystore \
-          -storepass android \
-          -dname 'CN=Android Debug,O=Android,C=US' \
-          -keyalg 'RSA' \
-          -keysize 2048 \
-          -validity 10000
+        # set up key.properties
+        echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
+        cat >> "$FCI_BUILD_DIR/android/key.properties" <<'EOF'
+        storePassword=$CM_KEYSTORE_PASSWORD
+        keyPassword=$CM_KEY_ALIAS_PASSWORD
+        keyAlias=$CM_KEY_ALIAS_USERNAME
+        storeFile=/tmp/keystore.keystore
+        EOF
       - |
         # set up local properties
         echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
+      - |
+        #!/usr/bin/env sh
+        set -e # exit on first failed commandset
+        echo $FCI_KEYSTORE_FILE | base64 --decode > $FCI_BUILD_DIR/app.keystore
       - flutter packages pub get
-      - flutter test
-      - flutter build apk --debug
+      - flutter build apk --release
     artifacts:
       - build/**/outputs/**/*.apk
       - build/**/outputs/**/*.aab
@@ -60,6 +69,19 @@ workflows:
       - build/**/outputs/**/*.apk
       - build/**/outputs/**/*.aab
       - build/**/outputs/**/mapping.txt
+      - flutter_drive.log
+    publishing:
+      email:
+        recipients:
+          - sbis1999@gmail.com
+  ios-workflow:
+    name: iOS Workflow
+    environment:
+      flutter: stable
+    scripts:
+      - flutter packages pub get
+      - flutter test
+    artifacts:
       - flutter_drive.log
     publishing:
       email:
